Updated all Records from CNR
eurodatacube/eodash pull request #527
Opened 2020-09-15 14:36 UTC by AlessandroScremin

Updated all records from CNR for NAS Region
Added RHO region timeseries from CNR

2020-09-17 05:56 UTC, aapopescu approved these changes

2020-09-18 06:20 UTC, aapopescu approved these changes

2020-09-18 06:24 UTC, aapopescu requested changes
The RHO delta is not here

2020-09-18 07:01 UTC, Schpidi commented
The RHO delta was not included so far in the trilateral version.

2020-09-18 07:04 UTC, aapopescu approved these changes

2020-09-18 09:05 UTC, merged

2020-09-18 09:13 UTC, AlessandroScremin commented
> The RHO delta is not here

@aapopescu 

> The RHO delta is not here

Sorry wrote RHO but would have said TSM....